default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: fourth_and_inches_development

test:
  <<: *default
  database: fourth_and_inches_test

production:
  <<: *default
  database: fourth_and_inches_production
  username: postgres
  password: mateo525

  # url: <%= ENV['DATABASE_URL'] %>
